/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_javaherobrine_GameUtils */

#ifndef _Included_io_github_javaherobrine_GameUtils
#define _Included_io_github_javaherobrine_GameUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_javaherobrine_GameUtils
 * Method:    address
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_io_github_javaherobrine_GameUtils_address___3B
  (JNIEnv *, jclass, jbyteArray);
JNIEXPORT void JNICALL Java_io_github_javaherobrine_GameUtils_allowGC
  (JNIEnv *, jclass, jlong, jbyteArray);
JNIEXPORT void JNICALL Java_io_github_javaherobrine_GameUtils_supportsNIOAccess
  (JNIEnv *, jclass, jobject);
JNIEXPORT void JNICALL Java_io_github_javaherobrine_GameUtils_to3x3
  (JNIEnv *, jclass, jobject);
JNIEXPORT jlong JNICALL Java_io_github_javaherobrine_GameUtils_pointerOfPointer
  (JNIEnv *, jclass, jlongArray);
JNIEXPORT void JNICALL Java_io_github_javaherobrine_GameUtils_freePointerOfPointer
  (JNIEnv *, jclass, jlong, jlongArray);
JNIEXPORT void JNICALL Java_io_github_javaherobrine_GameUtils_modelMatrix
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);
JNIEXPORT jlong JNICALL Java_io_github_javaherobrine_GameUtils_address__Ljava_nio_Buffer_2
  (JNIEnv *, jclass, jobject);
JNIEXPORT void JNICALL Java_io_github_javaherobrine_GameUtils_makeIdentity
  (JNIEnv *, jclass, jlong);
#ifdef __cplusplus
}
#endif
#endif
